"""initial migration

Revision ID: 1339404178ce
Revises: 
Create Date: 2026-03-17 18:08:15.795983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1339404178ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key.'),
    sa.Column('user_prompt', sa.Text(), nullable=False, comment='Request to the API.'),
    sa.Column('assistant_prompt', sa.Text(), nullable=False, comment='LLM model response.'),
    sa.Column('temperature', sa.Float(), nullable=False, comment='LLM model creativity param.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key.'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='User`s name.'),
    sa.Column('email', sa.String(length=50), nullable=False, comment='User`s email.'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Account creation date.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('api_key',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key.'),
    sa.Column('name', sa.Text(), nullable=False, comment='Key name.'),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Account creation date.'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_key')
    op.drop_table('user')
    op.drop_table('chat_history')
    # ### end Alembic commands ###
